name: Release alpha

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Create Alpha Release
        run: |
          git config --global user.email "bot@pomelloapp.com"
          git config --global user.name "pomello[bot]"
          npx standard-version --prerelease alpha --skip.changelog
          git push --follow-tags origin main
