name: Release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Create Release
        run: |
          git config --global user.email "bot@pomelloapp.com"
          git config --global user.name "pomello[bot]"
          npx standard-version
          git push --follow-tags origin main
